[WIP][TASK] Test new TypeScript Go (v7) preview
npm install --save-dev @typescript/native-preview patch-package

TODO:
 * lit decorators do not work properly, because
   `useDefineForClassFields` is still ignored, see
   https://github.com/microsoft/typescript-go/issues/785
 * ckeditor link plugin does not compile currently, which is why
   upstream is patched in this demo. Errors were:

   node_modules/@ckeditor/ckeditor5-engine/src/conversion/upcasthelpers.d.ts:26:13
   error TS8023: JSDoc '@extends module' does not match the 'extends ConversionHelpers' clause.

   26  * @extends module:engine/conversion/conversionhelpers~ConversionHelpers
                  ~~~~~~

   node_modules/@ckeditor/ckeditor5-ui/src/search/text/searchtextqueryview.d.ts:14:13
   error TS8023: JSDoc '@extends module' does not match the 'extends LabeledFieldView' clause.

   14  * @extends module:ui/labeledfield/labeledfieldview~LabeledFieldView
                   ~~~~~~

Releases: main
Change-Id: Ia2013dd9fb6f1488e779c3946aee5d017af6922f